apiVersion: v1
kind: Namespace
metadata:
  name: my-apps
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: envread-settings
  namespace: my-apps
data:
  app-config.json: |-
    {
      "environment": "Production",
      "serviceA": "https://my-apps.google.com/service-a",
      "serviceB": "https://my-apps.google.com/service-b",
      "serviceC": "https://my-apps.google.com/service-c/context-path"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-env-app
  namespace: my-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-env-app
  template:
    metadata:
      labels:
        app: multi-env-app
    spec:
      containers:
      - name: multi-env-app
        image: docker.io/chuckknorris/multi-env-app:2
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "400m"
            memory: "500Mi"
          requests:
            cpu: "200m"
            memory: "250Mi"
        volumeMounts:
          - name: envread-volume
            mountPath: /usr/share/nginx/html/assets/config/
      volumes:
      - name: envread-volume
        configMap:
          name: envread-settings
---
kind: Service
apiVersion: v1
metadata:
  name: multi-env-app
  namespace: my-apps
  labels:
    app: multi-env-app
spec:
  type: NodePort
  ports:
  - nodePort: 31317
    port: 80
    protocol: TCP
    targetPort: 80
    name: web
  selector:
    app: multi-env-app
